name: backend

on:
  push:
    branches:
      - main
  #pull_request:
  #  branches:
  #    - main
  # 定期実行の設定
  schedule:
   - cron: '0 12 * * *'

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - run: npm ci
      - run: npm run test -- --coverage
      - run: npm run build     

      # stepci dist/index.jsをバックグラウンド実行 & wait health check ok &next command exec
      - run: node dist/index.js &
      - run: npx wait-on -t 10000 http://localhost:8080/api/health
      - run: npm run test:api

      # upload artifact
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: backend/coverage/**
          retention-days: 5
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: backend/dist/index.js
          retention-days: 5
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu:latest
    steps:
      - run: rsync -v -e 'ssh -i ../../github-actions-key.pem' dist/index.js ubuntu@52.196.128.140:~/index.js
      - run: ssh -i ../../github-actions-key.pem ubuntu@52.196.128.140 sudo systemctl restart backend
      - run: ssh -i ../../github-actions-key.pem ubuntu@52.196.128.140 sudo systemctl start backend

